version: "3"

services:
  chatwizweb_node:
    image: chatwiz_web
    command:
      [
        "serve", "build"
      ]
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public

  chatwizweb_nginx:
    image: chatwiz_web_nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - chatwizweb_node
    restart: always
