version: "3"

services:

  chatwizweb_node:
    image: chatwizweb
    command:
      [
        "npm", "run", "start"
      ]
    ports:
      - 3000:3000

  chatwizweb_nginx:
    image: chatwiz_web_nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - chatwizweb_node